# Generated by Django 4.2.7 on 2023-11-04 04:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190220_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date(2023, 11, 4)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 11, 4)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 4, 4, 48, 26, 422838, tzinfo=datetime.timezone.utc), verbose_name='date_joined'),
        ),
    ]
