# Generated by Django 4.2.7 on 2024-03-10 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_end_date_alter_post_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.date(2024, 3, 10)),
        ),
        migrations.AlterField(
            model_name='post',
            name='start_date',
            field=models.DateField(default=datetime.date(2024, 3, 10)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 0, 42, 17, 378228, tzinfo=datetime.timezone.utc), verbose_name='date_joined'),
        ),
    ]
