# Generated by Django 4.2.7 on 2024-03-10 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_end_date_alter_post_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 10, 0, 43, 16, 449707, tzinfo=datetime.timezone.utc), verbose_name='date_joined'),
        ),
    ]
